version: "3"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=anarik
      - MONGO_PASSWORD=komarik
      - SESSION_SECRET=secret
      
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anarik
      - MONGO_INITDB_ROOT_PASSWORD=komarik
